video_upload:
    path:     /upload
    defaults: { _controller: VideoBundle:Upload:upload }

video_show:
    path:     /video/show/{video_Id}
    defaults: { _controller: VideoBundle:Video:show}

video_delete:
    path:     /delete/{id}
    defaults: { _controller: VideoBundle:Delete:delete }