services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    show_videos:
        class: VideoBundle\ShowVideo\ShowVideo
        arguments: [ "@doctrine.orm.entity_manager" ]

